### ISSUE TITLE
Error while reading Rom Folder

### ISSUE THREAD

**Issue by FeatherlessBiped** [TobiasKoller/RomSetManager#1]
This error came up when i tried to read source rom directory. Al seemed to be working in v1.02 but the features in the latest version are what i was after.
Windows 10 1903

![Annotation 2019-07-15 153703](https://user-images.githubusercontent.com/52936335/61247330-707efb80-a716-11e9-9a3e-4899b6ce0f10.png)

**Comment by TobiasKoller** [comment]
hi FeatherlessBiped,
thanks for the bugreport.

There was a problem when you choose a system from the list (choose systems-button) and there was not directory in your rom-directory-structure for that system.
I've fixed that in v1.0.4.

![image](https://user-images.githubusercontent.com/15647346/61266611-e033cb80-a794-11e9-945d-9df038aa9978.png)

Please try out this new version.
